---

# image details
image:
  repository: apache/nifi
  tag: "latest"
  pullPolicy: IfNotPresent
  imagePullSecret: ""

# security context as per user in nifi image
# This sets up the os-user security context to run the docker container
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# statefulset replica-count
replicaCount: 3

# Azure managed identity details
managedIdentity:
  enabled: false
  AzureIdentityBinding:
    selectorLabel: ""

# headless service
headless:
  type: ClusterIP
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

# ui service
service:
  type: ClusterIP
  port:
    http: 80
    https: 443
  annotations: {}
  sessionAffinity: "ClientIP"
  sessionAffinityTimeoutInSeconds: 60

ingress:
  enabled: true
  affinity: "cookie"
  affinityMode: "affinityMode"
  tlsVerifyDepth: 1
  user:
    name: "CN=proxyUser"
  tlsOnAnonymousNifi: false
  authenticateIngressOnAnonymousNifi: false
  tlsCerts:
    dir: certificates
    privateKey: ingress-tls.key
    certificate: ingress-tls.crt
    rootCaCertificate: ingress-root-ca.crt
  proxyCerts:
    # We would need certificate for ingress to authenticate itself to NiFi
    # These certificates would be required for ingress.user.name
    # One would need to provide these certificates when using user-provided certs for NiFi cluster
    dir: certificates
    privateKey: proxy-ingress-tls.key
    certificate: proxy-ingress-tls.crt

nifi:
  waitTimeToCheckNodeStatus: 30
  # Values for bootstrap.conf
  bootstrapConf:
    jvmMinMemory: 3g
    jvmMaxMemory: 3g
    g1ReservePercent: 20
    concGcThreads: 1
    parallelGcThreads: 1
    initiatingHeapOccupancyPercent: 35
  # Values for nifi.properties
  properties:
    networkInterface:
      default: eth0
      loopback: lo
      enableServiceOnLoopback: true
    port:
      http: 8080
      https: 8443
      cluster: 8081
    provenanceImplementation: org.apache.nifi.provenance.VolatileProvenanceRepository
    # performance parameters
    protocolThreads: 5
    maxProtocolThreads: 10
    clusterTimeout: 60
    zkTimeout: 15
    webProxyHost: DNSPREFIX.westeurope.cloudapp.azure.com
    # security parameters
    secured: false
  tls:
    certificateSource:
      nifiToolkit: false
      userProvided: false
    dir: certificates
    caCertificate: root_ca_certificate
    adminUser:
      enabled: true
      privateKey: admin_private_key
      certificate: admin_certificate
    nodeCerts:
      - node: 1
        privateKey: node1_private_key
        certificate: node1_certificate
      - node: 2
        privateKey: node2_private_key
        certificate: node2_certificate
      - node: 3
        privateKey: node3_private_key
        certificate: node3_certificate
    userCerts:
      # - user: 1
      #   certificate: user1_certificate
      # - user: 2
      #   certificate: user2_certificate
  # authentication parameters
  authentication:
    ldap:
      enabled: false
      tls:
        enabled: false
        certs:
          dir: "certificates"
          wildcard: true
          certificate: ldap-tls.crt
          privateKey: ldap-tls.key
          caCertificate: ldap-tls-ca.crt
        clientAuth: NONE
        protocol: TLS
        gracefulShutdown: false
      authenticationStrategy: "SIMPLE"
      referralStrategy: "FOLLOW"
      identityStrategy: "USE_USERNAME"
      url: ""
      managerDn: ""
      managerPassword: ""
      connectTimeout: "10 secs"
      readTimeout: "10 secs"
      userSearchBase: ""
      userSearchFilter: ""
      expirationPeriod: "12 hours"
    openid:
      enabled: false
      discoveryUrl: "https://login.microsoftonline.com/TENANTID/v2.0/.well-known/openid-configuration"
      clientId: ""
      clientSecret: ""
      additionalScopes: "profile, api://029455d7-fe07-43b4-a621-d7d9276e875a/.default"
      preferredJwsAlgorithm: ""
      claimIdentityingUser: ""
  authorization:
    adminUser:
      enabled: true
      name: "CN=admin"
    ldap:
      enforceCaseSensitivity: "false"
      syncInterval: "30 mins"
      pageSize: ""
      userObjectClass: ""
      userSearchScope: "ONE_LEVEL"
      userSearchFilter: ""
      userIdentityAttribute: "cn"
      userGroupNameAttribute: ""
      userReferencedGroupAttribute: ""
      groupSearchBase: ""
      groupObjectClass: ""
      groupSearchScope: "ONE_LEVEL"
      groupSearchFilter: ""
      groupNameAttribute: "cn"
      groupMemberAttribute: ""
      groupReferencedUserAttribute: ""
  initUsers:
    enabled: true
    admins:
      # Example user names should be put in quotes
      # - "CN=admin1"
      # - "admin2"
      # - "admin3@def.com"
      - "paul.latzelsperger@beardyinc.com"
    uiUsers:
      # Example user names should be put in quotes
      # - "user1"
      # - "CN=user2"
      # - "user3@def.com"
      - "paul.latzelsperger@beardyinc.com"

# pvc details
persistence:
  storageClass: default
  accessModes:  [ReadWriteOnce]
  configPartitionSize: 100Mi
  dataPartition1Size: 500Gi
  dataPartition2Size: 500Gi
  dataPartition3Size: 500Gi
  logPartitionSize: 5Gi

# Configure resource requests for nifi pods
resources:
  requests:
    memory: "1Gi"
    cpu: "0.9"

# Parameters for logging containers running in statefulset
logContainers:
  enabled: true
  image:
    repository: alpine
    pullPolicy: IfNotPresent
    tag: latest
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 50m
      memory: 50Mi

# nodeselector
nodeSelector: {}

# zookeeper details
zookeeper:
  enabled: true
  server: ""
  port: 2181
  image:
    repository: zookeeper
    pullPolicy: IfNotPresent
    tag: latest

# One can include additional libraries in the Nifi containers by using the postStart handler
# postStart is essentially a shell command one can execute on the pods coming up
# postStart: wget -P /opt/nifi/extensions/my.nar https://myLocation/my.nar

# ca server details
# Setting this true would create a nifi-toolkit based ca server
# The ca server will be used to generate self-signed certificates required setting up secured cluster
ca:
  server: ""
  port: 9090
  # TODO: token should be randomly generated randomly via secret
  token: sixteenCharacters
  image:
    repository: apache/nifi-toolkit
    pullPolicy: IfNotPresent
    tag: "latest"
    imagePullSecret: ""
