name: 'Discord Webhook'
on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened, reopened ]
  discussion:
    types: [ created ]

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/discord-webhook.yml@main
    with:
      event_discussion_html_url: ${{ github.event.discussion.html_url }}
      event_discussion_title: ${{ github.event.discussion.title }}
      event_issue_html_url: ${{ github.event.issue.html_url }}
      event_issue_title: ${{ github.event.issue.title }}
      event_name: ${{ github.event_name }}
      event_pull_request_html_url: ${{ github.event.pull_request.html_url }}
      event_pull_request_title: ${{ github.event.pull_request.title }}
      event_sender_avatar_url: ${{ github.event.sender.avatar_url }}
      event_sender_html_url: ${{ github.event.sender.html_url }}
      event_sender_login: ${{ github.event.sender.login }}
      repository_name: ${{ github.repository }}
    secrets:
      env_discord: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}