name: Generate OpenApi Spec

on: [ push, pull_request ]

jobs:
  GenerateOAS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Generate YAML spec
        env:
          INTEGRATION_TEST: false
        run: |
          ./gradlew clean resolve
          ./gradlew mergeOpenApiFiles
