name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request_target:

jobs:

  Azure-Integration-Test:
    # run only on upstream repo
    if: github.repository_owner == 'eclipse-dataspaceconnector'
    runs-on: ubuntu-latest

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports: [10000:10000]
        env:
          AZURITE_ACCOUNTS: account1:key1

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Object Storage StatusChecker Test
        env:
          RUN_INTEGRATION_TEST: true
        run: ./gradlew extensions:azure:blob:provision:check

      - name: CosmosDB Transfer Process Store Test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:transfer-process-store-cosmos:check

      - name: Cosmos-based Asset Index test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:assetindex-cosmos:check

      - name: Cosmos-based FCN Directory test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:fcc-node-directory-cosmos:check

      - name: Cosmos-based ContractDefinitionStore Test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:contract-definition-store-cosmos:check

      - name: Cosmos-based ContractNegotiationStore Test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:contract-negotiation-store-cosmos:check

  Aws-Integration-Test:
    # run only on upstream repo
    if: github.repository_owner == 'eclipse-dataspaceconnector'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: AWS S3 StatusChecker Test
        env:
          RUN_INTEGRATION_TEST: true
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        run: ./gradlew extensions:aws:s3:provision:check

  Daps-Integration-Test:
    runs-on: ubuntu-latest

    services:
      omejdn:
        image: ghcr.io/fraunhofer-aisec/omejdn-server:1.2.1
        ports:
          - 4567:4567
        volumes:
          - $PWD/extensions/iam/daps/src/test/resources/config:/opt/config
          - $PWD/extensions/iam/daps/src/test/resources/keys:/opt/keys

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Daps Integration Test
        env:
          RUN_INTEGRATION_TEST: true
        run: ./gradlew clean extensions:iam:daps:check