name: Integration Tests

# should only run on base branch, as secrets are not passed to runners
# when the PR comes from a fork
on: [ pull_request_target ]

jobs:
  Azure-Integration-Test:
    # run only on upstream repo
    if: github.repository_owner == 'eclipse-dataspaceconnector'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Object Storage StatusChecker Test
        env:
          RUN_INTEGRATION_TEST: true
          AZ_STORAGE_SAS: ${{ secrets.AZ_STORAGE_SAS }}
          AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
        run: ./gradlew extensions:azure:blob:provision:check

      - name: CosmosDB Transfer Process Store Test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:transfer-process-store-cosmos:check

      - name: Cosmos-based Asset Index test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:assetindex-cosmos:check


      - name: Cosmos-based FCN Directory test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:fcc-node-directory-cosmos:check

      - name: Cosmos-based ContractDefinitionStore Test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:contract-definition-store-cosmos:check

  Aws-Integration-Test:
    # run only on upstream repo
    if: github.repository_owner == 'eclipse-dataspaceconnector'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: AWS S3 StatusChecker Test
        env:
          RUN_INTEGRATION_TEST: true
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        run: ./gradlew extensions:aws:s3:provision:check