name: "Run Nightly Tests"
on:
  schedule:
    - "0 0 * * *" # run at 00:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Run-Dsp-Compatibility-Test:
    name: "Run DSP Compatibility Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: DSP Compatibility
        run: |
          ./gradlew -p system-tests/dsp-compatibility-tests test -DincludeTags="NightlyTest" -PverboseTest=true